export const catalogMenu = [
  {
    category: "Smartphone",
    icon: "i-heroicons-light-bulb",
    subcategories: [
      {
        title: "Laptops, tablets and e-readers",
        to: "home",
        items: [
          { label: "Laptops", to: "home" },
          { label: "Tablets", to: "home" },
          { label: "Accessories", to: "home" },
          { label: "E-books", to: "home" },
        ],
      },
      {
        title: "Computer equipment",
        to: "home",
        items: [
          { label: "Computer hardware", to: "home" },
          { label: "Computer accessories", to: "home" },
          { label: "Computer components", to: "home" },
          { label: "Computer peripherals", to: "home" },
          { label: "Data storage", to: "home" },
          { label: "Computers", to: "home" },
          { label: "Software", to: "home" },
        ],
      },
      {
        title: "Headphones and audio equipment",
        to: "home",
        items: [
          { label: "Headphones", to: "home" },
          { label: "Audio equipment", to: "home" },
          { label: "Accessories for players", to: "home" },
        ],
      },
      {
        title: "Peripherals and accessories",
        to: "home",
        items: [
          { label: "Photo and video equipment", to: "home" },
          { label: "Equipment for photographers", to: "home" },
          { label: "Photo and video cameras", to: "home" },
          { label: "Accessories for photo and video cameras", to: "home" },
        ],
      },
      {
        title: "Watches and electronic alarm clocks",
        to: "home",
        items: [
          { label: "Electronic alarm clocks", to: "home" },
          { label: "Projection clocks", to: "home" },
          { label: "Aroma alarm clocks and cartridges", to: "home" },
          { label: "Radio alarm clocks", to: "home" },
        ],
      },
      {
        title: "Smart home and security",
        to: "home",
        items: [
          { label: "Surveillance", to: "home" },
          { label: "Smart home", to: "home" },
          { label: "Home security", to: "home" },
        ],
      },
      {
        title: "TVs and video equipment",
        to: "home",
        items: [
          { label: "Cables and adapters", to: "home" },
          { label: "Tuners and receivers", to: "home" },
          { label: "Accessories for TVs", to: "home" },
          { label: "TVs", to: "home" },
          { label: "Stands and mounts for TVs", to: "home" },
          { label: "TV set-top boxes and media players", to: "home" },
          { label: "Projectors and accessories", to: "home" },
          { label: "Digital and satellite TV", to: "home" },
        ],
      },
      {
        title: "Quadcopters and accessories",
        to: "home",
        items: [
          { label: "Accessories", to: "home" },
          { label: "Quadcopters", to: "home" },
        ],
      },
      {
        title: "Game consoles and accessories",
        to: "home",
        items: [
          { label: "Game controllers", to: "home" },
          { label: "Consoles", to: "home" },
          {
            label: "Accessories and spare parts for game consoles",
            to: "home",
          },
          { label: "Games", to: "home" },
        ],
      },
      {
        title: "Navigators",
        to: "home",
        items: [{ label: "Car navigators", to: "home" }],
      },
      {
        title: "Office equipment",
        to: "home",
        items: [
          { label: "Office equipment components", to: "home" },
          { label: "Office equipment", to: "home" },
          {
            label: "Accessories and maintenance for office equipment",
            to: "home",
          },
        ],
      },
      {
        title: "Optical devices",
        to: "home",
        items: [
          { label: "Microscopes", to: "home" },
          { label: "Eyepieces", to: "home" },
          { label: "Telescopes", to: "home" },
          { label: "Theatrical binoculars", to: "home" },
          { label: "Accessories for microscopes", to: "home" },
          { label: "Accessories for telescopes", to: "home" },
        ],
      },
      {
        title: "Accessories for electronics",
        to: "home",
        items: [
          { label: "USB hubs", to: "home" },
          { label: "Battery chargers", to: "home" },
          { label: "Network filters", to: "home" },
          { label: "Battery cells", to: "home" },
          { label: "Extension cords", to: "home" },
          { label: "Cable holders", to: "home" },
          { label: "Voltage converters", to: "home" },
          { label: "Docking stations", to: "home" },
          { label: "Splitters", to: "home" },
          { label: "Cable organizers", to: "home" },
          { label: "Cable protection", to: "home" },
          { label: "Electrical splitters", to: "home" },
          { label: "Connectors", to: "home" },
          { label: "Solar panels and batteries", to: "home" },
          { label: "Wire boxes", to: "home" },
        ],
      },
    ],
  },
  {
    category: "Beauty",
    icon: "i-heroicons-light-bulb",
    subcategories: [
      {
        title: "Beauty equipment",
        to: "home",
        items: [
          { label: "Hair styling", to: "home" },
          { label: "Hair cutting", to: "home" },
          { label: "Electric shavers", to: "home" },
          { label: "Epilators and accessories", to: "home" },
          { label: "Cosmetology equipment", to: "home" },
          { label: "Floor scales", to: "home" },
          { label: "Mini-solariums", to: "home" },
        ],
      },
      {
        title: "Climate control equipment",
        to: "home",
        items: [
          { label: "Fans", to: "home" },
          { label: "Air purification and humidification", to: "home" },
          { label: "Air conditioners and split systems", to: "home" },
          { label: "Heaters", to: "home" },
          { label: "Water heaters and heating boilers", to: "home" },
          { label: "Sensors", to: "home" },
          { label: "Weather stations", to: "home" },
        ],
      },
      {
        title: "Major household appliances",
        to: "home",
        items: [
          { label: "Water coolers and accessories", to: "home" },
          { label: "Accessories for major household appliances", to: "home" },
          { label: "Refrigerators and freezers", to: "home" },
          { label: "Washing machines", to: "home" },
          { label: "Cookers", to: "home" },
          { label: "Kitchen hoods", to: "home" },
          { label: "Ovens", to: "home" },
          { label: "Cooktops", to: "home" },
          { label: "Dishwashers", to: "home" },
          { label: "Dryers", to: "home" },
          {
            label: "Other accessories and spare parts for household appliances",
            to: "home",
          },
        ],
      },
      {
        title: "Household appliances",
        to: "home",
        items: [
          { label: "Vacuum cleaners and accessories", to: "home" },
          { label: "Irons and steamers", to: "home" },
          { label: "Sewing machines and accessories", to: "home" },
          { label: "Wet cleaning devices", to: "home" },
          { label: "Sterilizers", to: "home" },
          { label: "Hand dryers", to: "home" },
        ],
      },
      {
        title: "Kitchen goods",
        to: "home",
        items: [
          { label: "Blenders and mixers", to: "home" },
          { label: "Electric kettles and thermo pots", to: "home" },
          { label: "Other kitchen appliances", to: "home" },
          { label: "Coffee machines and coffee makers", to: "home" },
          { label: "Microwaves and grills", to: "home" },
          { label: "Meat grinders and components", to: "home" },
          { label: "Dessert making equipment", to: "home" },
          { label: "Juicers", to: "home" },
          { label: "Hot plates", to: "home" },
          { label: "Cooking equipment", to: "home" },
          { label: "Toasters", to: "home" },
          { label: "Cooking food appliances", to: "home" },
          { label: "Kitchen combines", to: "home" },
          { label: "Accessories for kitchen appliances", to: "home" },
        ],
      },
    ],
  },
  {
    category: "Clothes",
    icon: "i-heroicons-light-bulb",
    subcategories: [
      {
        title: "Women's Clothing",
        to: "home",
        items: [
          { label: "Lingerie", to: "home" },
          { label: "Dresses and sundresses", to: "home" },
          { label: "T-shirts and polos", to: "home" },
          { label: "Socks, stockings, and tights", to: "home" },
          { label: "Trousers", to: "home" },
          { label: "Jumpers, sweaters, and cardigans", to: "home" },
          { label: "Blouses and shirts", to: "home" },
          { label: "Loungewear", to: "home" },
          { label: "Jeans", to: "home" },
          { label: "Sportswear", to: "home" },
          { label: "Swimwear and beachwear", to: "home" },
          { label: "Skirts", to: "home" },
          { label: "Tops and tank tops", to: "home" },
          { label: "Suits and sets", to: "home" },
          { label: "Hoodies and sweatshirts", to: "home" },
          { label: "Religious clothing for women", to: "home" },
          { label: "Outerwear", to: "home" },
          { label: "Jackets and suits", to: "home" },
          { label: "Tunics", to: "home" },
          { label: "Shorts", to: "home" },
          { label: "Maternity clothing", to: "home" },
          { label: "Jumpsuits", to: "home" },
          { label: "Bodysuits", to: "home" },
          { label: "National clothing", to: "home" },
          { label: "Knitted suits", to: "home" },
          { label: "Costumes and carnival clothing", to: "home" },
          { label: "Ski clothing", to: "home" },
          { label: "Plus size clothing", to: "home" },
          { label: "Workwear", to: "home" },
        ],
      },
      {
        title: "Men's Clothing",
        to: "home",
        items: [
          { label: "T-shirts and polos", to: "home" },
          { label: "Socks and hosiery", to: "home" },
          { label: "Trousers", to: "home" },
          { label: "Hoodies and sweatshirts", to: "home" },
          { label: "Jumpers, sweaters, and cardigans", to: "home" },
          { label: "Shirts", to: "home" },
          { label: "Jeans", to: "home" },
          { label: "Sportswear", to: "home" },
          { label: "Outerwear", to: "home" },
          { label: "Lingerie", to: "home" },
          { label: "Shorts", to: "home" },
          { label: "Workwear", to: "home" },
          { label: "Swimwear and swim shorts", to: "home" },
          { label: "Loungewear", to: "home" },
          { label: "Tops", to: "home" },
          { label: "Plus size clothing", to: "home" },
          { label: "Thermal underwear", to: "home" },
          { label: "Jackets and suits", to: "home" },
          { label: "Carnival costumes", to: "home" },
          { label: "Religious clothing for men", to: "home" },
          { label: "National clothing", to: "home" },
        ],
      },
      {
        title: "Children's Clothing",
        to: "home",
        items: [
          { label: "Clothing for girls", to: "home" },
          { label: "Clothing for boys", to: "home" },
          { label: "Newborn clothing", to: "home" },
        ],
      },
    ],
  },
];
